# site settings
title: Hidden Quarter
subtitle: 
email: info@hiddenquarter.com
description: Custom Solutions
baseurl: #/hiddenquarter # the subpath of your site, e.g. /blog
url: //hiddenquarter.com # the base hostname & protocol for your site
author:
street_address: 
city: Boise
state: Idaho
zip_code: 
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/randomdude583
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/alex-collette-591714146/
pinterest_url:
slack_url:
twitter_url: 
pubdev_url: https://pub.dev/publishers/hiddenquarter.com/packages

# build settings
markdown: kramdown

sass:
  style: compressed


# Google services
google_analytics: UA-167823832-1