# Site settings
title: Hidden Quarter
subtitle: 
email: info@hiddenquarter.com
description: Apps made by us, for you.
baseurl: /hiddenquarter
url: http://randomdude583.github.io # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

collections:
  appPages:
    output: true
  404Page:
    output: true

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# Apps tiles
app-tiles-count: 2

# Social settings
500px_url:
facebook_url: https://www.facebook.com/SplytMusic.co/ 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/splytmusic_co?lang=en

# Google analytics
google_analytics: UA-88119269-1

# Build settings
markdown: kramdown
